// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzr-8Nlr3xWq7Wm_4ECuATvsGQhGy4ViE',
    appId: '1:48521747253:web:a6366f0f9d0996a2b6ca7c',
    messagingSenderId: '48521747253',
    projectId: 'aichatbot-d1a52',
    authDomain: 'aichatbot-d1a52.firebaseapp.com',
    storageBucket: 'aichatbot-d1a52.firebasestorage.app',
    measurementId: 'G-S3N11VWRLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa4AiGg8I9ACwJn6rOqSNeqPnjkaE45hc',
    appId: '1:48521747253:android:dd6386f97b5a3ab2b6ca7c',
    messagingSenderId: '48521747253',
    projectId: 'aichatbot-d1a52',
    storageBucket: 'aichatbot-d1a52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK_8-JhHpvoFYixttgyBk6Qyjvcdu0WlU',
    appId: '1:48521747253:ios:6669c4afab7aa537b6ca7c',
    messagingSenderId: '48521747253',
    projectId: 'aichatbot-d1a52',
    storageBucket: 'aichatbot-d1a52.firebasestorage.app',
    iosClientId: '48521747253-cti84c55mjr1a06r68s5slv7jp3nacmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK_8-JhHpvoFYixttgyBk6Qyjvcdu0WlU',
    appId: '1:48521747253:ios:6669c4afab7aa537b6ca7c',
    messagingSenderId: '48521747253',
    projectId: 'aichatbot-d1a52',
    storageBucket: 'aichatbot-d1a52.firebasestorage.app',
    iosClientId: '48521747253-cti84c55mjr1a06r68s5slv7jp3nacmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzr-8Nlr3xWq7Wm_4ECuATvsGQhGy4ViE',
    appId: '1:48521747253:web:e5b39c7f5d68cb4cb6ca7c',
    messagingSenderId: '48521747253',
    projectId: 'aichatbot-d1a52',
    authDomain: 'aichatbot-d1a52.firebaseapp.com',
    storageBucket: 'aichatbot-d1a52.firebasestorage.app',
    measurementId: 'G-C4X8F05F9T',
  );
}
